package ru.anb.passwordapp.features.ui.interest.model

import ru.anb.passwordapp.R

import java.util.Locale

data class Interest(
    var mImageLink: String? = null,
    var mInterestName: String? = null,
    var mInterestType: String? = null,
    var mInterestClicked: Boolean = false
) {

    fun itemClicked() {
        mImageLink = "none"
        mInterestName = "clicked"
    }

    fun getLocalizedName(): String {
        return when (Locale.getDefault().language) {
            "ru" -> russianNameMap[mInterestName] ?: mInterestName ?: ""
            else -> mInterestName ?: ""
        }
    }

    companion object {
        private val russianNameMap = mapOf(
            "Astronomy" to "Астрономия",
            "Biology" to "Биология",
            "Chemistry" to "Химия",
            "Computer Programming" to "Программирование",
            "Geography" to "География",
            "History" to "История",
            "Literature" to "Литература",
            "Mathematics" to "Математика",
            "Physics" to "Физика",
            "Psychology" to "Психология",
            "Railway studies" to "Железнодорожное дело",
            "Science and technology studies" to "Наука и технология",
            "Social studies" to "Обществознание",
            "Sports science" to "Спортивная наука",
            "3D printing" to "3D-печать",
            "Acrobatics" to "Акробатика",
            "Acting" to "Актёрское мастерство",
            "Amateur radio" to "Любительское радио",
            "Animal fancy" to "Разведение животных",
            "Animation" to "Анимация",
            "Aquascaping" to "Акваскейпинг",
            "Astrology" to "Астрология",
            "Astronomy" to "Астрономия",
            "Audiophile" to "Аудиофилия",
            "Axe throwing" to "Метание топора",
            "Backgammon" to "Нарды",
            "Badminton" to "Бадминтон",
            "Baking" to "Выпечка",
            "Baton twirling" to "Вращение жезла",
            "Beauty pageants" to "Конкурсы красоты",
            "Billiards" to "Бильярд",
            "Blogging" to "Ведение блога",
            "Board/tabletop games" to "Настольные игры",
            "Book discussion clubs" to "Книжные клубы",
            "Book restoration" to "Реставрация книг",
            "Bowling" to "Боулинг",
            "Boxing" to "Бокс",
            "Brazilian jiu-jitsu" to "Бразильское джиу-джитсу",
            "Breadmaking" to "Хлебопечение",
            "Bridge" to "Бридж",
            "Building" to "Строительство",
            "Bullet journaling" to "Ведение дневника",
            "Cabaret" to "Кабаре",
            "Calligraphy" to "Каллиграфия",
            "Candle making" to "Изготовление свечей",
            "Candy making" to "Изготовление конфет",
            "Car fixing & building" to "Ремонт и тюнинг автомобилей",
            "Card games" to "Карточные игры",
            "Checkers" to "Шашки",
            "Cheesemaking" to "Сыроварение",
            "Chess" to "Шахматы",
            "Cleaning" to "Уборка",
            "Coffee roasting" to "Обжарка кофе",
            "Collecting" to "Коллекционирование",
            "Color guard" to "Цветная гвардия",
            "Coloring" to "Раскрашивание",
            "Computer programming" to "Программирование",
            "Confectionery" to "Кондитерское дело",
            "Cooking" to "Готовка",
            "Cosplaying" to "Косплей",
            "Craft" to "Рукоделие",
            "Creative writing" to "Литературное творчество",
            "Crocheting" to "Вязание крючком",
            "Cross-stitch" to "Вышивка крестиком",
            "Crossword puzzles" to "Кроссворды",
            "Cryptography" to "Криптография",
            "Cue sports" to "Бильярдные виды спорта",
            "Curling" to "Кёрлинг",
            "DJing" to "Ди-джеинг",
            "Dance" to "Танцы",
            "Dancing" to "Танцы",
            "Darts" to "Дартс",
            "Debate" to "Дебаты",
            "Digital arts" to "Цифровое искусство",
            "Distro Hopping" to "Смена дистрибутивов Linux",
            "Do it yourself" to "Сделай сам",
            "Dominoes" to "Домино",
            "Drama" to "Драматургия",
            "Drawing" to "Рисование",
            "Drink mixing" to "Смешивание напитков",
            "Eating" to "Дегустация еды",
            "Electronic games" to "Электронные игры",
            "Electronics" to "Электроника",
            "Embroidery" to "Вышивание",
            "Esports" to "Киберспорт",
            "Experimenting" to "Экспериментирование",
            "Fantasy sports" to "Фэнтези-спорт",
            "Fashion" to "Мода",
            "Fashion design" to "Дизайн одежды",
            "Fencing" to "Фехтование",
            "Filmmaking" to "Кинопроизводство",
            "Fishkeeping" to "Аквариумистика",
            "Flower arranging" to "Икебана",
            "Fly tying" to "Вязание мушек",
            "Foreign language learning" to "Изучение языков",
            "Furniture building" to "Изготовление мебели",
            "Gaming" to "Видеоигры",
            "Genealogy" to "Генеалогия",
            "Gingerbread house making" to "Изготовление пряничных домиков",
            "Glassblowing" to "Выдувание стекла",
            "Graphic design" to "Графический дизайн",
            "Gymnastics" to "Гимнастика",
            "Hacking" to "Хакерство",
            "Herp keeping" to "Содержание рептилий",
            "Home improvement" to "Ремонт дома",
            "Houseplant care" to "Уход за комнатными растениями",
            "Hula hooping" to "Хулахуп",
            "Humor" to "Юмор",
            "Hydroponics" to "Гидропоника",
            "Ice hockey" to "Хоккей",
            "Ice skating" to "Катание на коньках",
            "Jewelry making" to "Изготовление украшений",
            "Jigsaw puzzles" to "Пазлы",
            "Journaling" to "Ведение дневника",
            "Judo" to "Дзюдо",
            "Juggling" to "Жонглирование",
            "Karaoke" to "Караоке",
            "Karate" to "Карате",
            "Knife making" to "Изготовление ножей",
            "Knitting" to "Вязание",
            "Knot tying" to "Вязание узлов",
            "Knowledge/word games" to "Интеллектуальные игры",
            "Kombucha brewing" to "Приготовление комбучи",
            "Lace making" to "Кружевоплетение",
            "Lapidary" to "Обработка камней",
            "Laser tag" to "Лазертаг",
            "Learning" to "Обучение",
            "Leather crafting" to "Работа с кожей",
            "Lego building" to "Сборка Lego",
            "Listening to music" to "Прослушивание музыки",
            "Listening to podcasts" to "Прослушивание подкастов",
            "Lock picking" to "Вскрытие замков",
            "Longboarding" to "Лонгбординг",
            "Machining" to "Обработка металла",
            "Macrame" to "Макраме",
            "Magic" to "Фокусы",
            "Mahjong" to "Маджонг",
            "Makeup" to "Макияж",
            "Marbles" to "Игра в шарики",
            "Martial arts" to "Боевые искусства",
            "Mazes" to "Лабиринты",
            "Meditation" to "Медитация",
            "Metalworking" to "Металлообработка",
            "Microscopy" to "Микроскопия",
            "Model United Nations" to "Модель ООН",
            "Model building" to "Моделирование",
            "Model engineering" to "Инженерное моделирование",
            "Model racing" to "Гонки моделей",
            "Nail art" to "Дизайн ногтей",
            "Needlepoint" to "Вышивание иглой",
            "Origami" to "Оригами",
            "Painting" to "Живопись",
            "Palmistry" to "Хиромантия",
            "Pet adoption & fostering" to "Усыновление питомцев",
            "Philately" to "Филателия",
            "Photography" to "Фотография",
            "Playing musical instruments" to "Игра на музыкальных инструментах",
            "Poi" to "Пои",
            "Poker" to "Покер",
            "Pool" to "Пул",
            "Pottery" to "Гончарное дело",
            "Powerlifting" to "Пауэрлифтинг",
            "Practical jokes" to "Розыгрыши",
            "Pressed flower craft" to "Ошибана",
            "Puzzles" to "Головоломки",
            "Quilting" to "Лоскутное шитьё",
            "Quizzes" to "Викторины",
            "Radio-controlled model" to "Радиоуправляемые модели",
            "Rail transport modeling" to "Моделирование железных дорог",
            "Rapping" to "Рэп",
            "Reading" to "Чтение",
            "Reiki" to "Рэйки",
            "Research" to "Исследования",
            "Robot combat" to "Бои роботов",
            "Role-playing games" to "Ролевые игры",
            "Rubik's Cube" to "Кубик Рубика",
            "Scrapbooking" to "Скрапбукинг",
            "Sculpting" to "Скульптура",
            "Sewing" to "Шитьё",
            "Shoemaking" to "Изготовление обуви",
            "Shogi" to "Сёги",
            "Shortwave listening" to "Коротковолновое радиолюбительство",
            "Singing" to "Пение",
            "Sketching" to "Наброски",
            "Skipping rope" to "Прыжки на скакалке",
            "Slot car" to "Автомодели с треком",
            "Slot car racing" to "Гонки автомоделей",
            "Social media" to "Социальные сети",
            "Speedcubing" to "Спидкубинг",
            "Sport stacking" to "Спортивная пирамида",
            "Spreadsheets" to "Электронные таблицы",
            "Stamp collecting" to "Филателия",
            "Stand-up comedy" to "Стендап",
            "Table football" to "Настольный футбол",
            "Table tennis" to "Настольный теннис",
            "Tarot" to "Таро",
            "Taxidermy" to "Таксидермия",
            "Thrifting" to "Шопинг в секонд-хендах",
            "Video editing" to "Видеомонтаж",
            "Video game developing" to "Разработка видеоигр",
            "Video gaming" to "Видеоигры",
            "Videography" to "Видеосъёмка",
            "Virtual reality" to "Виртуальная реальность",
            "Volleyball" to "Волейбол",
            "Watching movies" to "Просмотр фильмов",
            "Watching television" to "Просмотр телевизора",
            "Waxing" to "Депиляция воском",
            "Weaving" to "Ткачество",
            "Weight training" to "Тренировки с весом",
            "Weightlifting" to "Тяжёлая атлетика",
            "Welding" to "Сварка",
            "Whittling" to "Резьба по дереву",
            "Wikipedia editing" to "Редактирование Википедии",
            "Winemaking" to "Виноделие",
            "Wood carving" to "Резьба по дереву",
            "Woodworking" to "Столярное дело",
            "Word searches" to "Поиск слов",
            "Wrestling" to "Борьба",
            "Writing" to "Письмо",
            "Yo-yoing" to "Йо-йо",
            "Yoga" to "Йога",
            "Zumba" to "Зумба",
            "Air sports" to "Авиационные виды спорта",
            "Airsoft" to "Страйкбол",
            "Amateur geology" to "Любительская геология",
            "Archery" to "Стрельба из лука",
            "Association football" to "Футбол",
            "Astronomy" to "Астрономия",
            "Australian rules football" to "Австралийский футбол",
            "Auto racing" to "Автогонки",
            "BASE jumping" to "Бейсджампинг",
            "BMX" to "BMX",
            "Backpacking" to "Пеший туризм",
            "Badminton" to "Бадминтон",
            "Baseball" to "Бейсбол",
            "Basketball" to "Баскетбол",
            "Beach volleyball" to "Пляжный волейбол",
            "Beekeeping" to "Пчеловодство",
            "Birdwatching" to "Наблюдение за птицами",
            "Board sports" to "Досковые виды спорта",
            "Bodybuilding" to "Бодибилдинг",
            "Bonsai" to "Бонсай",
            "Breakdancing" to "Брейкданс",
            "Bus riding" to "Езда на автобусе",
            "Butterfly watching" to "Наблюдение за бабочками",
            "Camping" to "Кемпинг",
            "Canoeing" to "Гребля на каноэ",
            "Canyoning" to "Каньонинг",
            "Car riding" to "Езда на автомобиле",
            "Caving" to "Спелеология",
            "Climbing" to "Скалолазание",
            "Composting" to "Компостирование",
            "Cricket" to "Крикет",
            "Croquet" to "Крокет",
            "Cycling" to "Велоспорт",
            "Disc golf" to "Диск-гольф",
            "Dog sport" to "Спорт с собаками",
            "Driving" to "Вождение",
            "Equestrianism" to "Конный спорт",
            "Exhibition drill" to "Строевая подготовка",
            "Farming" to "Фермерство",
            "Field hockey" to "Хоккей на траве",
            "Figure skating" to "Фигурное катание",
            "Fishing" to "Рыбалка",
            "Flag football" to "Флаг-футбол",
            "Flower growing" to "Выращивание цветов",
            "Flying" to "Пилотирование",
            "Flying disc" to "Летающий диск",
            "Foraging" to "Собирательство",
            "Freestyle football" to "Фристайл-футбол",
            "Frisbee" to "Фрисби",
            "Gardening" to "Садоводство",
            "Geocaching" to "Геокэшинг",
            "Ghost hunting" to "Охота на привидений",
            "Gold prospecting" to "Поиск золота",
            "Golfing" to "Гольф",
            "Graffiti" to "Граффити",
            "Handball" to "Гандбол",
            "Herbalism" to "Травничество",
            "Herping" to "Наблюдение за рептилиями",
            "Highpower rocketry" to "Ракетомоделизм",
            "Hiking" to "Пеший туризм",
            "Hobby horsing" to "Хоббихорсинг",
            "Hobby tunneling" to "Туннелирование как хобби",
            "Hooping" to "Хулахуп",
            "Horseback riding" to "Верховая езда",
            "Horseshoes" to "Подковы",
            "Hunting" to "Охота",
            "Iceboat racing" to "Гонки на буерах",
            "Inline skating" to "Катание на роликах",
            "Jogging" to "Бег трусцой",
            "Jumping rope" to "Прыжки со скакалкой",
            "Kart racing" to "Картинг",
            "Kayaking" to "Гребля на байдарках",
            "Kite flying" to "Запуск воздушных змеев",
            "Kitesurfing" to "Кайтсёрфинг",
            "Knife throwing" to "Метание ножей",
            "LARPing" to "Ролевые игры",
            "Lacrosse" to "Лакросс",
            "Longboarding" to "Лонгбординг",
            "Longdistance running" to "Бег на длинные дистанции",
            "Marching band" to "Оркестр марширующих",
            "Martial arts" to "Боевые искусства",
            "Metal detecting" to "Металлоискательство",
            "Meteorology" to "Метеорология",
            "Model aircraft" to "Авиамоделирование",
            "Motor sports" to "Мотоспорт",
            "Mountain biking" to "Горный велоспорт",
            "Mountaineering" to "Альпинизм",
            "Museum visiting" to "Посещение музеев",
            "Netball" to "Нетбол",
            "Nordic skating" to "Северные коньки",
            "Orienteering" to "Ориентирование",
            "Paintball" to "Пейнтбол",
            "Parkour" to "Паркур",
            "Photography" to "Фотография",
            "Pickleball" to "Пиклбол",
            "Podcast hosting" to "Ведение подкастов",
            "Polo" to "Поло",
            "Powerboat racing" to "Гонки на моторных лодках",
            "Public transport riding" to "Езда на общественном транспорте",
            "Quidditch" to "Квиддич",
            "Race walking" to "Спортивная ходьба",
            "Racquetball" to "Ракетбол",
            "Radiocontrolled car racing" to "Гонки на радиоуправляемых машинах",
            "Radiocontrolled model" to "Радиоуправляемые модели",
            "Rafting" to "Рафтинг",
            "Railway journeys" to "Железнодорожные путешествия",
            "Rappelling" to "Спуск по верёвке",
            "Road biking" to "Шоссейный велоспорт",
            "Rock climbing" to "Скалолазание",
            "Roller derby" to "Роллер-дерби",
            "Roller skating" to "Катание на роликах",
            "Rugby" to "Регби",
            "Rugby league football" to "Регбилиг",
            "Running" to "Бег",
            "Sailing" to "Парусный спорт",
            "Sand art" to "Песочное искусство",
            "Scouting" to "Скаутинг",
            "Scuba diving" to "Дайвинг",
            "Sculling or rowing" to "Академическая гребля",
            "Shooting" to "Стрельба",
            "Shooting sport" to "Стрелковый спорт",
            "Shopping" to "Шопинг",
            "Shuffleboard" to "Шаффлборд",
            "Skateboarding" to "Скейтбординг",
            "Skiing" to "Лыжный спорт",
            "Skimboarding" to "Скимбординг",
            "Skydiving" to "Прыжки с парашютом",
            "Slacklining" to "Слэклайн",
            "Sled dog racing" to "Гонки на собачьих упряжках",
            "Snowboarding" to "Сноубординг",
            "Snowmobiling" to "Езда на снегоходах",
            "Snowshoeing" to "Ходьба на снегоступах",
            "Soccer" to "Футбол",
            "Softball" to "Софтбол",
            "Speed skating" to "Конькобежный спорт",
            "Squash" to "Сквош",
            "Stone skipping" to "Запуск камешков по воде",
            "Sun bathing" to "Солнечные ванны",
            "Surfing" to "Сёрфинг",
            "Survivalism" to "Выживание",
            "Swimming" to "Плавание",
            "Table tennis" to "Настольный теннис",
            "Taekwondo" to "Тхэквондо",
            "Tai chi" to "Тайцзи",
            "Tennis" to "Теннис",
            "Tennis polo" to "Теннис-поло",
            "Tether car" to "Тетеркар",
            "Topiary" to "Топиари",
            "Tour skating" to "Тур-коньки",
            "Tourism" to "Туризм",
            "Trade fair visiting" to "Посещение ярмарок",
            "Travel" to "Путешествия",
            "Triathlon" to "Триатлон",
            "Ultimate frisbee" to "Алтимат фрисби",
            "Urban exploration" to "Сталкерство",
            "Vacation" to "Отдых",
            "Vegetable farming" to "Овощеводство",
            "Vehicle restoration" to "Реставрация автомобилей",
            "Videography" to "Видеосъёмка",
            "Volleyball" to "Волейбол",
            "Walking" to "Ходьба",
            "Water polo" to "Водное поло",
            "Water sports" to "Водные виды спорта"
        )

    }
}
